pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '$(solution)'
    configuration: '$(buildConfiguration)'
    arguments: '--configuration $(buildConfiguration) -p:Platform="$(buildPlatform)"'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(solution)'
    configuration: '$(buildConfiguration)'
    arguments: '--configuration $(buildConfiguration) -p:Platform="$(buildPlatform)"'
